// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hyperapp from "hyperapp";

function add(s) {
  return {
          firstNumber: s.firstNumber + 1 | 0,
          secondNumber: s.secondNumber
        };
}

Hyperapp.app({
      node: document.getElementById("app"),
      init: {
        firstNumber: 1,
        secondNumber: 0
      },
      view: (function (state) {
          var string = String(state.firstNumber);
          return Hyperapp.h("div", {
                      onclick: add
                    }, Hyperapp.text("hello world! " + string));
        })
    });

export {
  add ,
  
}
/*  Not a pure module */
