// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hyperapp from "hyperapp";

function add(oldState) {
  var newObj = Object.assign(oldState, {
        firstNumber: oldState.firstNumber + 1 | 0
      });
  console.log(newObj);
  return newObj;
}

Hyperapp.app({
      node: document.getElementById("app"),
      init: {
        firstNumber: 1
      },
      view: (function (state) {
          console.log(state);
          return Hyperapp.h("div", {
                      onclick: add
                    }, Hyperapp.text("hello world! " + state.firstNumber));
        })
    });

export {
  add ,
  
}
/*  Not a pure module */
