// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hyperapp from "hyperapp";

function updateState(oldState, newState) {
  return Object.assign({}, Object.assign(oldState, newState));
}

function add(s, param) {
  return updateState(s, {
              firstNumber: s.firstNumber + 1 | 0
            });
}

Hyperapp.app({
      node: document.getElementById("app"),
      init: {
        firstNumber: 1
      },
      view: (function (state) {
          return Hyperapp.h("div", {
                      onclick: add
                    }, Hyperapp.text("hello world! " + state.firstNumber));
        })
    });

export {
  updateState ,
  add ,
  
}
/*  Not a pure module */
